# Generated by Django 2.2 on 2019-04-23 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190423_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 12, 0, 37, 210797, tzinfo=utc)),
        ),
    ]
