# Generated by Django 2.2 on 2019-05-01 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190501_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 23, 52, 53, 761068, tzinfo=utc)),
        ),
    ]
