# Generated by Django 2.2 on 2019-05-08 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190506_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 10, 55, 2, 630894, tzinfo=utc)),
        ),
    ]
