# Generated by Django 2.2 on 2019-05-10 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190510_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_by',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 19, 24, 40, 218190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 19, 24, 40, 218190, tzinfo=utc)),
        ),
    ]
