# Generated by Django 2.2 on 2019-05-03 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 5, 3, 12, 42, 54, 356594, tzinfo=utc))),
                ('image', models.ImageField(default='demo.jpg', upload_to='demo_pics')),
            ],
        ),
    ]
