# Generated by Django 2.2 on 2019-05-07 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_sm',
            field=models.ImageField(default='demo.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 2, 20, 29, 565276, tzinfo=utc)),
        ),
    ]
