# Generated by Django 2.2 on 2019-05-08 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190506_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 10, 55, 2, 646517, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_sm',
            field=models.ImageField(default='demo.jpg', upload_to='demo_pics'),
        ),
    ]
