# Generated by Django 2.2 on 2019-05-09 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20190508_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 22, 9, 7, 47488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_sm',
            field=models.ImageField(default='demo.jpg', upload_to='demo_pics_sm'),
        ),
    ]
