# Generated by Django 2.2 on 2019-05-10 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20190509_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_created',
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 0, 57, 1, 179436, tzinfo=utc)),
        ),
    ]
