# Generated by Django 2.2 on 2019-05-10 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20190509_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 13, 2, 49, 5115, tzinfo=utc)),
        ),
    ]
