# Generated by Django 2.2 on 2019-05-10 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20190510_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 19, 24, 40, 233814, tzinfo=utc)),
        ),
    ]
